### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Mesmer88** [ssorgatem/Octoprint-Filament-Reloaded#15] opened 2023-01-23 18:09 UTC
Trying to install this on latest octopi + octoprint (1.8.6) but getting this error and plugin gets disabled automatically:

```
2023-01-23 19:59:42,627 - octoprint.plugin.core - WARNING - Plugin Octoprint-filamentreload (1.4.0) can't be compiled under Python 3.7.3 due to invalid syntax
2023-01-23 19:59:42,663 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2023-01-23 19:59:42,707 - octoprint.plugin.core - ERROR - Invalid syntax in plugin file of plugin filamentreload
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 782, in _parse_metadata
    return parse_plugin_metadata(self.location)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 78, in parse_plugin_metadata
    root = ast.parse(f.read(), filename=path)
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_filamentreload/__init__.py", line 183
    return {
           ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by alexandrenorman** [comment] 2023-01-23 19:44
Issue fixed in this pull request : https://github.com/nickmitchko/Octoprint-Filament-Reloaded/pull/14
I have done a zip you can install with the following url : https://seafile.xael.org/f/3db4f4d966a14a6984fa/?dl=1

**Comment by nickmitchko** [comment] 2023-01-30 22:19
Sorry, I've been afk. looks good and I merged the PR

**Comment by robbrad** [comment] 2023-01-30 22:48
@nickmitchko - I get a new error now with this version ( happy to open a new issue)

https://pastebin.com/DaGfgDym

`  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_filamentreload/__init__.py", line 93, in pullup
    return int(self._settings.get(["pullup"] or 0))
`

**Comment by robbrad** [comment] 2023-01-30 23:11
Should this 
https://github.com/nickmitchko/Octoprint-Filament-Reloaded/blob/9ec4020513625450f6097274dd61ade759a7a909/octoprint_filamentreload/__init__.py#L93

be :

` return int(self._settings.get(["pullup"] ,0))`

**Comment by nickmitchko** [comment] 2023-01-30 23:26
Thanks for spot checking this, I'll reopen and test on my instance

**Comment by robbrad** [comment] 2023-01-30 23:28
My understanding is incorrect its not an or value on the mixin I think it just needs a default adding im testing now

**Comment by robbrad** [comment] 2023-01-30 23:32
@nickmitchko : This makes the plugin work (well OP loads at least) https://github.com/robbrad/Octoprint-Filament-Reloaded/commit/3f1ed06b6601f01cf2f2b86d7df967e62bec5c61

But is doing this the desired behaviour?

~~I dont have a working sensor yet - I have to build one. So im unable to do a full e2e test~~

**Comment by nickmitchko** [comment] 2023-01-30 23:38
@robbrad Just need to determine if that makes pullup always 0

**Comment by robbrad** [comment] 2023-01-30 23:40
OK Confirmed it works on my system - it can be changed in settings (but it initialised as 0 for first install)

**Comment by robbrad** [comment] 2023-01-30 23:48
![image](https://user-images.githubusercontent.com/6122503/215623365-9c3dca55-c036-4fad-9e4a-f40d4d080fa1.png)

Shows out of Filament ! which is good because it is !

**Comment by robbrad** [comment] 2023-01-30 23:53
and with filament 
![image](https://user-images.githubusercontent.com/6122503/215623270-bbe3fd92-2601-42de-a7c3-51c71d51abbd.png)

**Comment by robbrad** [comment] 2023-01-31 00:05
@nickmitchko - I just tested 1.4.1 and unfortunatly the same issue happens on clean install `  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_filamentreload/__init__.py", line 93, in pullup
    return int(self._settings.get(["pullup"])) or 0
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`

**Comment by nickmitchko** [comment] 2023-01-31 00:19
Odd behavior as there must be a change in octoprint between 1.8.6 and 1.8.1. I took your PR since all the code changes work on my test printer (octopi 1.8.1 and python 3.7.3).

Testing again now as 1.4.2.

**Comment by robbrad** [comment] 2023-01-31 00:24
1.4.2 works for me

**Comment by nickmitchko** [comment] 2023-01-31 00:34
Nice, glad this is fixed up.

**Closed as completed by nickmitchko** 2023-01-31 00:34 UTC
